=== basting/Quantra/xsdFiles/railway.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="railway">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="train" type="TrainDetails" maxOccurs="50"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:complexType name="TrainDetails">
	<xs:sequence>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="no" type="xs:integer"/>
		<xs:element name="from" type="xs:string"/>
		<xs:element name="to" type="xs:string"/>
		<xs:element name="type" type="xs:string"/>
		<xs:element name="time" type="xs:time"/>
		<xs:element name="duration" type="xs:decimal"/>
		<xs:element name="reservation" type="Reservation_Details" maxOccurs="100"/>
		<xs:element name="route" type="RouteDetails"/>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="RouteDetails">
	<xs:sequence>
		<xs:element name="via" type="xs:string"/>
		<xs:element name="length" type="xs:decimal"/>
		<xs:element name="no_of_stations" type="xs:integer"/>
		<xs:element name="starting_zone" type="Zone_Details"/>
		<xs:element name="ending_zone" type="Zone_Details"/>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="Reservation_Details">
	<xs:sequence>
		<xs:element name="serial_no" type="xs:integer"/>
		<xs:element name="date" type="xs:date"/>
		<xs:element name="class" type="xs:string"/>
		<xs:element name="from" type="xs:string"/>
		<xs:element name="to" type="xs:string"/>
		<xs:element name="passenger" type="Person_Details" maxOccurs="10"/>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="Person_Details">
	<xs:sequence>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="age" type="xs:integer"/>
		<xs:element name="sex" type="xs:string"/>
		<xs:element name="address" type="xs:string"/>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="Zone_Details">
	<xs:sequence>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="no_of_states" type="xs:decimal"/>
	</xs:sequence>
</xs:complexType>
</xs:schema>

=== basting/Quantra/xmlFiles/NewFile.xml
<train xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsdFiles/railway.xsd">
    <name>Parasuram</name>
    <no>201</no>
    <from>Trivandrum</from>
    <to>Kasarcode</to>
    <type>Express</type>
    <start>05:00:00</start>
    <duration>20.0</duration>
    <reservation>
      <serial_no>123201</serial_no>
      <date>2005-03-05</date>
      <class>Second</class>
      <from>Trivandrum</from>
      <to>Palakkad</to>
      <passenger>
        <name>BGH</name>
        <age>21</age>
        <sex>Male</sex>
        <address>Deepthi</address>
      </passenger>
    </reservation>
     <route>
    <via>Kottayam</via>
    <type_of_track>Broadgauge</type_of_track>
    <length>720.0</length>
    <no_of_stations>49</no_of_stations>
    <starting_zone>
      <name>southzone</name>
      <no_of_states>4.0</no_of_states>
    </starting_zone>
    <ending_zone>
      <name>southzone</name>
      <no_of_states>4.0</no_of_states>
    </ending_zone>
  </route>
  </train>
